# Scans image for vulnerabilities; If policy evaluation fails, then build fails
# Must configure required environment variables
version: 0.2

env:
  parameter-store:
    SECURE_API_TOKEN: /CodeBuild/SYSDIG_API_TOKEN
    SYSDIG_API_ENDPOINT: /CodeBuild/SYSDIG_API_URL

phases:
  install:
    commands:
      # Download most recent version of Sysdig CLI Scanner
      - curl -LO https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)/linux/amd64/sysdig-cli-scanner
      - chmod +x ./sysdig-cli-scanner
      
  build:
    commands:
      - docker build -t nginx-hello:hello1 .
      
  post_build:
    commands:
      - pwd
      - ./sysdig-cli-scanner --apiurl=$SYSDIG_API_ENDPOINT --output-json=sysdig-scan-report.json nginx-hello:hello1

artifacts:
  files:
    - 'sysdig-scan-report.json'
    
